### ISSUE TITLE
Run App Local

### ISSUE THREAD

**Issue by mOrfiUs** [Ibrajber99/LuminMovies#1]
Great App. Can you provide a step-by-step guide to compile and run in local mode?
Obviously APIKey from TMDB
Prerequisites(SQL, MySQL, SQLite,...)
Connection string...
etc..
I try to run, but i need Connection String...
thanks in advance

**Comment by Ibrajber99** [comment]
Hello,

You won't require any connection string for a database connection.
All the data is directly coming from the API (No Caching).

All you need to do is clone the repo. Add the API key and, run the solution.

**Comment by mOrfiUs** [comment]
![image](https://user-images.githubusercontent.com/4864108/114269832-48b2e980-9a09-11eb-83e2-06c17e86fe9b.png)

Thanks for reply. Only MoviesDataBase.Web is availabe trough repo.
If Download as Zip MovieDatabase.LocalClientAi is included in zip, but MovieDataBase.ClientAPI and MovieDataBase.Models are disappear.

**Comment by Ibrajber99** [comment]
Hell, yes. i just noticed that. im reuploading the correct project files and i will add instructions on how to run it.
sorry for the inconvenience

**Comment by mOrfiUs** [comment]
Thanks again!!

**Comment by Ibrajber99** [comment]
Instructions have been added and I updated the folders.
please let me know if it works. Thank you.

**Comment by mOrfiUs** [comment]
Now work fine. Issue solved. Perhaps, absolute and relative path problem?
In my humble opinion, the covers are very large. Six per row (screen 1920x1080) are better. It's just a suggestion.
Congratulations for your App.

**Comment by Ibrajber99** [comment]
Glad it's working.
Yes, it's the paths and also the reference IDs were malformed.
Thank you for your feedback. 
The front-end side of things is not my expertise, but if you want to fix the I and improve upon please do and, let me know how it looks.

**Comment by mOrfiUs** [comment]
OK. I Suggest delete your API Key. I  deleted yours from my download, and now i use mine. Thanks Ibrahim.

**Comment by Ibrajber99** [comment]
Oh thanks for pointing that out.
